# Generated by Django 4.1.3 on 2022-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=40)),
                ('curso_asignado', models.CharField(max_length=20)),
                ('fechaInicio', models.DateField(max_length=40)),
                ('fechatermino', models.DateField(max_length=10)),
                ('saldo', models.IntegerField(max_length=1000000)),
            ],
        ),
    ]
