# Generated by Django 4.1.3 on 2022-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0002_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
