# Generated by Django 4.1.3 on 2022-12-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0003_alter_apoderado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='templatesApp.profesor'),
            preserve_default=False,
        ),
    ]
