# Generated by Django 4.1.3 on 2022-12-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0004_apoderado_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='profesor',
        ),
    ]
